In [ ]:
import sqlite3

# Create a connection to the SQLite database
conn = sqlite3.connect('example.db')    
# Create a cursor object to interact with the database
cursor = conn.cursor()
# Create a table named 'users' if it doesn't exist
cursor.execute('''CREATE TABLE IF NOT EXISTS users
                  (id INTEGER PRIMARY KEY, name TEXT UNIQUE, age INTEGER UNIQUE)''')
# Insert a new user into the 'users' table  
cursor.execute("INSERT INTO users (name, age) VALUES (?, ?)", ('Alice', 30))
# Commit the changes to the database
conn.commit()
# Query the 'users' table to retrieve all users
cursor.execute("SELECT * FROM users")
# Fetch all results from the executed query
users = cursor.fetchall()
# Print the retrieved users
print(users)
# Close the database connection
conn.close()

In [2]:
name = input("Enter name: ")

special_chars = "!@#$%^&*()_+=-`~"

if any(char in special_chars for char in name):
    print("Name contains special characters.", name)

elif len(name) < 3:
    print("Name is too short.", name)

elif len(name) > 20:
    print("Name is too long.", name)

else:
    print("Name is valid.", name)

Name is valid. asdgh

In [1]:
print("Validation complete.")

Validation complete.

In [ ]:
import sqlite3 

conn = sqlite3.connect("Ankit.db")
cursor = conn.cursor()

conn.execute("""
        create table student (
                   Stu_id INTEGER AUTO_INCREMENT PRIMARY KEY,
                   Stu_Name TEXT,
                   Stu_Age   INTEGER,
                   
                   Stu_Course TEXT,
                   Stu_Marks INTEGER )              
                       """)
print("Table Created Successfully")
conn.close()

In [15]:
#Creating DB
import sqlite3 
conn = sqlite3.connect("Employees.db")
cursor = conn.cursor()

#Creating Table
cursor.execute("""
                       Create table Employees1(
                                                        Emp_Id INTEGER PRIMARY KEY AUTOINCREMENT,
                                                         Emp_Name TEXT,
                                                         Emp_Age INTEGER,
                                                         Emp_Department TEXT,
                                                         Emp_Salary INTEGER
                                                          )
                          """)
print("Table created successfully ")

#Inserting multiple records

data = [
            (1,"Ankit", 23,"AIA AISQUAD",100),
            (2,"Ram", 22,"Life Science",20),
            (3,"Syham", 34,"AIA ",10),
            (4,"Raju", 89,"Insurance",9000),
            (5,"Bheem", 35," AISQUAD",10000),
            (6,"Karan", 45,"Cyber Security",28800),
            (7,"Salman", 70,"Banking",1300),
             (8,"Sharukhan", 45,"Finance",800)]

cursor.executemany("INSERT INTO Employees VALUES (?,?,?,?,?)" , data)

print("Records inserted successfully")
conn.commit()
conn.close()

Table created successfully
Records inserted successfully

In [12]:
#Reading all data from the table
import sqlite3
conn = sqlite3.connect("Employees.db")
cursor = conn.cursor()
print("Opened database successfully")
cursor.execute("SELECT * FROM Employees")
ankit = cursor.fetchall()
print(ankit)
conn.close()

Opened database successfully
[(1, 'Ankit', 23, 'AIA AISQUAD', 100), (2, 'Ram', 22, 'Life Science', 20), (4, 'Raju', 89, 'Insurance', 9000), (5, 'Bheem', 35, ' AISQUAD', 10000), (7, 'Salman', 70, 'Banking', 1300), (8, 'Sharukhan', 45, 'Finance', 800), (10, 'Karan', 45, 'Cyber Security', 28800)]

In [21]:
# Deleting a record from the table

import sqlite3
conn = sqlite3.connect("Employees.db")
cursor = conn.cursor()
x = 3   
cursor.execute(" Delete from Employees where Emp_Id = ?",(x,))
print("Record deleted successfully")
conn.commit()
conn.close()

Record deleted successfully

In [2]:
print("Hi Ankit")

Hi Ankit

In [11]:
# pandas 
import pandas as pd
conn = sqlite3.connect('Employees.db')
# dataframe is a structure to hold tabular data
df = pd.read_sql_query("select * from Employees", conn)

df.head(20)

   Emp_Id   Emp_Name  Emp_Age  Emp_Department  Emp_Salary
0       1      Ankit       23     AIA AISQUAD         100
1       2        Ram       22    Life Science          20
2       4       Raju       89       Insurance        9000
3       5      Bheem       35         AISQUAD       10000
4       7     Salman       70         Banking        1300
5       8  Sharukhan       45         Finance         800
6      10      Karan       45  Cyber Security       28800

In [7]:
#updating a record in the table
import sqlite3
conn = sqlite3.connect("Employees.db")
cursor = conn.cursor()
cursor.execute("UPDATE Employees SET Emp_Id = 10 WHERE Emp_Name = 'Karan'")
print("Record updated successfully")
conn.commit()
conn.close()

Record updated successfully

In [18]:
#Reading all data from the table
import sqlite3
conn = sqlite3.connect("Employees.db")
cursor = conn.cursor()
cursor.execute("SELECT * FROM Employees ")
print("All records from the Employees table:")
records = cursor.fetchall() 
print(records)  
conn.close()

All records from the Employees table:
[(1, 'Ankit', 23, 'AIA AISQUAD', 100), (2, 'Ram', 22, 'Life Science', 20), (3, 'Kohli', 44, 'Cricketer', 49), (4, 'Raju', 89, 'Insurance', 9000), (5, 'Bheem', 35, ' AISQUAD', 10000), (7, 'Salman', 70, 'Banking', 1300), (8, 'Sharukhan', 45, 'Finance', 800), (10, 'Karan', 45, 'Cyber Security', 28800)]

In [17]:
#inserting a record into the table
import sqlite3
conn = sqlite3.connect("Employees.db")
cursor = conn.cursor()
cursor.execute("INSERT INTO Employees  VALUES (?, ?, ?, ?, ?)", (3, 'Kohli', 44, 'Cricketer', 49))
print("Record inserted successfully")
conn.commit()
conn.close()

Record inserted successfully

In [ ]:
import sqlite3
conn

In [27]:
import pandas as  pd
conn = sqlite3.connect("Employees.db")

df = pd.read_sql_query("Select * from Employees", conn)

df.head(20)

   Emp_Id   Emp_Name  Emp_Age  Emp_Department  Emp_Salary
0       1      Ankit       23     AIA AISQUAD         100
1       2        Ram       22    Life Science          20
2       3      Kohli       44       Cricketer          49
3       4       Raju       89       Insurance        9000
4       5      Bheem       35         AISQUAD       10000
5       6     Salman       70         Banking        1300
6       7  Sharukhan       45         Finance         800
7       8      Karan       45  Cyber Security       28800

In [26]:
import sqlite3
conn = sqlite3.connect("Employees.db")
cursor = conn.cursor()
cursor.execute("Update Employees set Emp_Id = 7 where Emp_Name = 'Sharukhan'")
cursor.execute("Update Employees set Emp_Id = 8 where Emp_Name = 'Karan'")
print("Record updated successfully")
conn.commit()
conn.close()

Record updated successfully

In [29]:
import pandas as AG
conn = sqlite3.connect("Employees.db")
df = AG.read_sql_query("Select * from Employees", conn)
df.head(20)

   Emp_Id   Emp_Name  Emp_Age  Emp_Department  Emp_Salary
0       1      Ankit       23     AIA AISQUAD         100
1       2        Ram       22    Life Science          20
2       3      Kohli       44       Cricketer          49
3       4       Raju       89       Insurance        9000
4       5      Bheem       35         AISQUAD       10000
5       6     Salman       70         Banking        1300
6       7  Sharukhan       45         Finance         800
7       8      Karan       45  Cyber Security       28800

**Regrlar Expression**

In [40]:
# searching a word
import re

pattern = "My name is raju sarkar , raju bhai have 2 apples and 3 oranges"
x = re.search("raju", pattern)
if x:
    print("Word found in the string.")  
else:
    print("Word not found in the string.")

Word found in the string.

In [66]:
#finding all the words in the string
import re
pattern = "My name is raju sarkar , raju bhai have 2 apples and 3 oranges"
x = re.findall("raju", pattern)
print(x)

['raju', 'raju']

In [12]:
#finding digits in a string
import re
pattern = "My name is raju sarkar , raju bhai have 2 apples and 3 oranges"
x = re.findall(r"\d", pattern)
print(x)

['2', '3']

In [68]:
#Substituting a digits in a string
import re
pattern = "My name is raju sarkar , raju bhai have 2 apples and 3 oranges"
new_pattern = re.sub(r"\d+", "X", pattern)
print(new_pattern)

My name is raju sarkar , raju bhai have X apples and X oranges

In [69]:
#Substituting a word in a string
import re 
pattern = "My name is raju sarkar , raju bhai have 2 apples and 3 oranges"
new_pattern = re.sub("raju", "Ankit", pattern)
print(new_pattern)

My name is Ankit sarkar , Ankit bhai have 2 apples and 3 oranges

In [76]:
#split function in regular expression
import re 
pattern = "My name is raju sarkar , raju bhai have 2 apples and 3 oranges"
x = re.split(r"\s", pattern)
print(x)

['My', 'name', 'is', 'raju', 'sarkar', ',', 'raju', 'bhai', 'have', '2', 'apples', 'and', '3', 'oranges']

In [78]:
#reverse a string
word = "Ankit"
reversed_word = word[::-1]
print(reversed_word)

tiknA

In [ ]:
#slice object 
list = [1, 2, 3, 4, 5, 40, 50, 60, 70, 80, 90, 100]
x = slice(2,7,2)
print(list[x])

[3, 5, 50]

In [ ]:
#lambda function
add = lambda a,b : a + b
print(add(10,13))

23

In [84]:
num = [1, 2, 3, 4, 5]
result = []
for i in num:
    result.append(i*2)
print(result)

[2, 4, 6, 8, 10]

In [7]:
#list comprehension
marks = [10, 20, 30, 40, 50]
result = [x + 2 for x in marks]
print(result)

[12, 22, 32, 42, 52]

In [ ]:
#list comprehension using if condition 
easy = [ X ** 3 for X in range(10) if X % 2 == 0]
print("Cube roots of even numbers from 0 to 9:",easy)

Cube roots of even numbers from 0 to 9: [0, 8, 64, 216, 512]

In [11]:
#list comprehension using if else condition
Check = [f"{x} =  Even" if x % 2 == 0 else f"{x} = Odd" for x in range(10)]
print(Check)

['0 =  Even', '1 = Odd', '2 =  Even', '3 = Odd', '4 =  Even', '5 = Odd', '6 =  Even', '7 = Odd', '8 =  Even', '9 = Odd']

In [17]:
#iterators
my_list = [1, 2, 3, 4, 5]
my_iterator = iter(my_list)
print(next(my_iterator))
print(next(my_iterator))

1
2

In [18]:
string = "Hello World"
print(string[8])

r

In [21]:
list = [1, 2, 3, 4, 5]
new_list = iter(list)
print(next(new_list))
print(next(new_list))

1
2

In [ ]:
#import json 
data = {
    "name": "Ankit",
    "age": 23,
    "city": "Bangalore"
}
print(data)
print(type(data))

{'name': 'Ankit', 'age': 23, 'city': 'Bangalore'}
<class 'dict'>

In [58]:
import json 

data = {
    "name": "Ankit",
    "age": 23,
    "city": "Bangalore"
}
new = json.dumps(data)
print(new)
print(type(new))

{"name": "Ankit", "age": 23, "city": "Bangalore"}
<class 'str'>

In [52]:
import json 
data = '{"name": "Ankit", "age": 23, "city": "Bangalore"}'
#new = json.loads(data)
#print(new)
#print(type(new))
print(data)
print(type(data))

{"name": "Ankit", "age": 23, "city": "Bangalore"}
<class 'str'>

In [64]:
import json

with open("josn.json", "r") as file:
    data = json.load(file)  
print(data)

{'system': {'name': 'Enterprise Data Platform', 'version': '3.4.7', 'environment': 'production', 'timestamp': '2026-05-13T15:30:00Z', 'region': 'ap-south-1', 'status': {'uptime_seconds': 98765432, 'health': 'green', 'services': [{'name': 'auth-service', 'status': 'running', 'latency_ms': 12}, {'name': 'data-ingestion', 'status': 'running', 'latency_ms': 34}, {'name': 'analytics-engine', 'status': 'degraded', 'latency_ms': 120}]}}, 'users': [{'user_id': 'USR_1001', 'profile': {'name': 'Ankit Vishwakarma', 'email': 'ankit.v@example.com', 'roles': ['data_engineer', 'analyst'], 'organization': {'name': 'Cognizant', 'department': 'AI & Analytics', 'location': 'Mumbai'}}, 'permissions': {'access_level': 'admin', 'allowed_modules': ['etl', 'dashboard', 'ml_pipeline'], 'feature_flags': {'beta_features': True, 'advanced_ai': False}}, 'activity': {'last_login': '2026-05-12T09:18:45Z', 'login_history': [{'ip': '192.168.1.10', 'device': 'Laptop', 'timestamp': '2026-05-12T09:18:45Z'}, {'ip': '192.168.1.11', 'device': 'Mobile', 'timestamp': '2026-05-11T20:45:12Z'}]}}], 'data_pipeline': {'pipelines': [{'pipeline_id': 'PIPE_001', 'name': 'Sales_ETL_Pipeline', 'schedule': {'cron': '0 */6 * * *', 'timezone': 'Asia/Kolkata'}, 'stages': [{'stage': 'extract', 'source': {'type': 'sql', 'connection': {'host': 'db.prod.internal', 'port': 5432, 'database': 'sales_db'}, 'query': "SELECT * FROM transactions WHERE updated_at > NOW() - INTERVAL '6 HOURS'"}}, {'stage': 'transform', 'operations': [{'type': 'filter', 'condition': 'amount > 0'}, {'type': 'map', 'script': 'normalize_currency'}, {'type': 'aggregate', 'group_by': ['region'], 'metrics': ['sum(amount)']}]}, {'stage': 'load', 'destination': {'type': 'data_warehouse', 'target_table': 'dw_sales_summary', 'mode': 'upsert'}}], 'metrics': {'last_run': '2026-05-13T12:00:00Z', 'duration_sec': 320, 'records_processed': 152034, 'error_count': 2}}]}, 'analytics': {'dashboards': [{'dashboard_id': 'DASH_9001', 'name': 'Revenue Insights', 'widgets': [{'type': 'line_chart', 'title': 'Monthly Revenue', 'data_source': 'dw_sales_summary', 'config': {'x_axis': 'month', 'y_axis': 'revenue', 'filters': {'region': ['APAC', 'EMEA']}}}, {'type': 'kpi', 'title': 'Total Revenue', 'value': 2540000, 'thresholds': {'warning': 2000000, 'critical': 1500000}}]}], 'ml_models': [{'model_id': 'ML_202', 'name': 'Sales Forecasting', 'type': 'time_series', 'status': 'active', 'accuracy': 0.92, 'parameters': {'algorithm': 'Prophet', 'seasonality': ['weekly', 'yearly'], 'confidence_interval': 0.95}}]}, 'security': {'audit_logs': [{'event_id': 'EVT_001', 'user_id': 'USR_1001', 'action': 'LOGIN_SUCCESS', 'timestamp': '2026-05-12T09:18:45Z', 'ip_address': '192.168.1.10'}, {'event_id': 'EVT_002', 'user_id': 'USR_1001', 'action': 'DATA_EXPORT', 'timestamp': '2026-05-12T10:05:22Z', 'details': {'file': 'sales_data.csv', 'records': 5000}}], 'policies': {'password_policy': {'min_length': 12, 'require_special_char': True, 'expiry_days': 90}, 'encryption': {'at_rest': 'AES-256', 'in_transit': 'TLS 1.3'}}}, 'metadata': {'schema_version': 'v2.1', 'created_by': 'system_admin', 'created_at': '2026-01-01T00:00:00Z', 'tags': ['enterprise', 'etl', 'analytics', 'ml', 'secure']}}

In [56]:
import json

data = '{"name": "Ankit"}'

result = json.loads(data)

print(result)
print(type(result))

{'name': 'Ankit'}
<class 'dict'>

In [ ]:
import json

data = {"name": "Ankit"}

with open("json.json", "w") as f:
    json.dump(data, f)
print("Data written to json file successfully.")

Data written to json file successfully.

In [ ]:
#Reading data from a json file
import json

with open("Ankit.json","r") as f:
    data = json.load(f)
    print(data,["name"][0])

{'system': {'name': 'Enterprise Data Platform', 'version': '3.4.7', 'environment': 'production', 'timestamp': '2026-05-13T15:30:00Z', 'region': 'ap-south-1', 'status': {'uptime_seconds': 98765432, 'health': 'green', 'services': [{'name': 'auth-service', 'status': 'running', 'latency_ms': 12}, {'name': 'data-ingestion', 'status': 'running', 'latency_ms': 34}, {'name': 'analytics-engine', 'status': 'degraded', 'latency_ms': 120}]}}, 'users': [{'user_id': 'USR_1001', 'profile': {'name': 'Ankit Vishwakarma', 'email': 'ankit.v@example.com', 'roles': ['data_engineer', 'analyst'], 'organization': {'name': 'Cognizant', 'department': 'AI & Analytics', 'location': 'Mumbai'}}, 'permissions': {'access_level': 'admin', 'allowed_modules': ['etl', 'dashboard', 'ml_pipeline'], 'feature_flags': {'beta_features': True, 'advanced_ai': False}}, 'activity': {'last_login': '2026-05-12T09:18:45Z', 'login_history': [{'ip': '192.168.1.10', 'device': 'Laptop', 'timestamp': '2026-05-12T09:18:45Z'}, {'ip': '192.168.1.11', 'device': 'Mobile', 'timestamp': '2026-05-11T20:45:12Z'}]}}], 'data_pipeline': {'pipelines': [{'pipeline_id': 'PIPE_001', 'name': 'Sales_ETL_Pipeline', 'schedule': {'cron': '0 */6 * * *', 'timezone': 'Asia/Kolkata'}, 'stages': [{'stage': 'extract', 'source': {'type': 'sql', 'connection': {'host': 'db.prod.internal', 'port': 5432, 'database': 'sales_db'}, 'query': "SELECT * FROM transactions WHERE updated_at > NOW() - INTERVAL '6 HOURS'"}}, {'stage': 'transform', 'operations': [{'type': 'filter', 'condition': 'amount > 0'}, {'type': 'map', 'script': 'normalize_currency'}, {'type': 'aggregate', 'group_by': ['region'], 'metrics': ['sum(amount)']}]}, {'stage': 'load', 'destination': {'type': 'data_warehouse', 'target_table': 'dw_sales_summary', 'mode': 'upsert'}}], 'metrics': {'last_run': '2026-05-13T12:00:00Z', 'duration_sec': 320, 'records_processed': 152034, 'error_count': 2}}]}, 'analytics': {'dashboards': [{'dashboard_id': 'DASH_9001', 'name': 'Revenue Insights', 'widgets': [{'type': 'line_chart', 'title': 'Monthly Revenue', 'data_source': 'dw_sales_summary', 'config': {'x_axis': 'month', 'y_axis': 'revenue', 'filters': {'region': ['APAC', 'EMEA']}}}, {'type': 'kpi', 'title': 'Total Revenue', 'value': 2540000, 'thresholds': {'warning': 2000000, 'critical': 1500000}}]}], 'ml_models': [{'model_id': 'ML_202', 'name': 'Sales Forecasting', 'type': 'time_series', 'status': 'active', 'accuracy': 0.92, 'parameters': {'algorithm': 'Prophet', 'seasonality': ['weekly', 'yearly'], 'confidence_interval': 0.95}}]}, 'security': {'audit_logs': [{'event_id': 'EVT_001', 'user_id': 'USR_1001', 'action': 'LOGIN_SUCCESS', 'timestamp': '2026-05-12T09:18:45Z', 'ip_address': '192.168.1.10'}, {'event_id': 'EVT_002', 'user_id': 'USR_1001', 'action': 'DATA_EXPORT', 'timestamp': '2026-05-12T10:05:22Z', 'details': {'file': 'sales_data.csv', 'records': 5000}}], 'policies': {'password_policy': {'min_length': 12, 'require_special_char': True, 'expiry_days': 90}, 'encryption': {'at_rest': 'AES-256', 'in_transit': 'TLS 1.3'}}}, 'metadata': {'schema_version': 'v2.1', 'created_by': 'system_admin', 'created_at': '2026-01-01T00:00:00Z', 'tags': ['enterprise', 'etl', 'analytics', 'ml', 'secure']}} name

In [9]:
import json

data = {
    "name": "Ankit",}
with open("Data.json","w") as f:
    x = json.dump(data,f)
    print("data written to json file successfully")

data written to json file successfully